name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Deploy target (github_pages or custom_domain)'
        required: true
        default: 'github_pages'
        type: choice
        options:
          - github_pages
          - custom_domain

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Build for custom domain if specified in workflow_dispatch
      - name: Build for custom domain
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_target == 'custom_domain' }}
        env:
          DEPLOY_ENV: "CUSTOM_DOMAIN"
        run: npm run build

      # Default build for GitHub Pages
      - name: Build for GitHub Pages
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.deploy_target != 'custom_domain' }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.website_workflow }}
          publish_dir: ./out