name: Deploy site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Build Next.js (static export)
        env:
          DEPLOY_ENV: CUSTOM_DOMAIN
        run: |
          npm run build

      - name: Build Progress (Vite) app
        working-directory: public/progress
        run: |
          npm ci || npm install
          npm run build

      - name: Bundle Progress app into export (preserve dist folder and redirecting index)
        run: |
          rm -rf out/progress
          mkdir -p out/progress
          # Keep the built app under /progress/dist
          mkdir -p out/progress/dist
          cp -r public/progress/dist/* out/progress/dist/
          # Copy the source redirecting index and manifest to /progress
          cp public/progress/index.html out/progress/index.html
          cp public/progress/manifest.webmanifest out/progress/manifest.webmanifest
          # Copy icons and any static assets expected at root
          if [ -f public/progress/public/favicon.svg ]; then cp public/progress/public/favicon.svg out/progress/; fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Add CNAME (if present)
        run: |
          if [ -f public/CNAME ]; then cp public/CNAME out/CNAME; fi
          if [ -f public/progress/CNAME ]; then cp public/progress/CNAME out/CNAME; fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
